// Coleção local de disciplinas, renderizada com .map() na tela de Disciplinas.
// Cada disciplina também traz os dados usados na tela de detalhe (/disciplinas/:id).
export const disciplinas = [
  {
    id: 'calculo-ii',
    nome: 'Cálculo II',
    professor: 'Prof. Marco Silva',
    status: 'Em curso',
    emDestaque: true,
    rotuloProgresso: 'Progresso',
    progresso: 60,
    codigo: 'MAT-201',
    cargaHoraria: '80h',
    semestre: '3º período',
    descricao:
      'Integrais, técnicas de integração, séries e funções de várias variáveis, com aplicações em problemas de engenharia.',
    aulas: [
      { id: 1, titulo: 'Integrais definidas e indefinidas', concluida: true },
      { id: 2, titulo: 'Técnicas de integração', concluida: true },
      { id: 3, titulo: 'Aplicações da integral', concluida: true },
      { id: 4, titulo: 'Séries e sequências', concluida: false },
      { id: 5, titulo: 'Funções de várias variáveis', concluida: false },
    ],
  },
  {
    id: 'estatistica-aplicada',
    nome: 'Estatística Aplicada',
    professor: 'Dra. Helena Costa',
    status: 'Em curso',
    emDestaque: true,
    rotuloProgresso: 'Progresso',
    progresso: 45,
    codigo: 'EST-110',
    cargaHoraria: '60h',
    semestre: '3º período',
    descricao:
      'Estatística descritiva, probabilidade, distribuições e inferência aplicadas à análise de dados.',
    aulas: [
      { id: 1, titulo: 'Estatística descritiva', concluida: true },
      { id: 2, titulo: 'Probabilidade', concluida: true },
      { id: 3, titulo: 'Distribuições de probabilidade', concluida: false },
      { id: 4, titulo: 'Testes de hipótese', concluida: false },
    ],
  },
  {
    id: 'front-end',
    nome: 'Front-end',
    professor: 'Prof. Lucas Vergara',
    status: 'Em curso',
    emDestaque: true,
    rotuloProgresso: 'Progresso',
    progresso: 75,
    codigo: 'ENG-330',
    cargaHoraria: '80h',
    semestre: '5º período',
    descricao:
      'Desenvolvimento de interfaces web modernas com HTML, CSS, JavaScript e React.',
    aulas: [
      { id: 1, titulo: 'Fundamentos de HTML e CSS', concluida: true },
      { id: 2, titulo: 'JavaScript e manipulação do DOM', concluida: true },
      { id: 3, titulo: 'Introdução ao React', concluida: true },
      { id: 4, titulo: 'Hooks e Context API', concluida: true },
      { id: 5, titulo: 'Roteamento e consumo de API', concluida: false },
    ],
  },
  {
    id: 'banco-de-dados-ii',
    nome: 'Banco de Dados II',
    professor: 'Prof. Rafael Souza',
    status: 'Em curso',
    emDestaque: true,
    rotuloProgresso: 'Progresso',
    progresso: 30,
    codigo: 'BD-220',
    cargaHoraria: '60h',
    semestre: '4º período',
    descricao:
      'Modelagem avançada, otimização de consultas, transações e bancos de dados não relacionais.',
    aulas: [
      { id: 1, titulo: 'Revisão de SQL', concluida: true },
      { id: 2, titulo: 'Índices e otimização de consultas', concluida: false },
      { id: 3, titulo: 'Transações e concorrência', concluida: false },
      { id: 4, titulo: 'Bancos NoSQL', concluida: false },
    ],
  },
  {
    id: 'criatividade-e-inovacao',
    nome: 'Criatividade e Inovação',
    professor: 'Dra. Ana Lúcia',
    status: 'Próximo semestre',
    emDestaque: false,
    rotuloProgresso: 'Disponibilidade',
    progresso: 0,
    codigo: 'INO-100',
    cargaHoraria: '40h',
    semestre: '6º período',
    descricao:
      'Métodos de geração de ideias, design thinking e desenvolvimento de soluções inovadoras.',
    aulas: [
      { id: 1, titulo: 'Design thinking', concluida: false },
      { id: 2, titulo: 'Prototipação de ideias', concluida: false },
      { id: 3, titulo: 'Modelos de negócio', concluida: false },
    ],
  },
]
